# Generated by Django 4.1.7 on 2023-04-04 20:38

import coreplus.utils.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discuss",
            fields=[
                (
                    "created",
                    coreplus.utils.models.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    coreplus.utils.models.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Commented object id.",
                        max_length=54,
                        null=True,
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "content_html",
                    models.TextField(editable=False, verbose_name="Content HTML"),
                ),
                (
                    "reaction",
                    models.JSONField(
                        blank=True,
                        help_text='JSON fields contains {"like": 1, "love":2, "flap":3}',
                        null=True,
                        verbose_name="reaction",
                    ),
                ),
                (
                    "flag",
                    models.JSONField(
                        blank=True,
                        editable=False,
                        help_text='JSON fields contains {"spam": 1, "hoax":2, "bullying":3}',
                        null=True,
                        verbose_name="flag",
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to="apps.application",
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        help_text="Discuss can have a hierarchy, totally optional.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="discuss.discuss",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discuss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discuss",
                "verbose_name_plural": "Discuss",
            },
        ),
    ]
